apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deploy
  labels:
    app: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
     app: mydb
  template:
    metadata:
     name: maria-pod
     labels:
      app: mydb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: password

