apiVersion: v1
kind: ReplicationController
metadata: 
  name: httpd-rc
spec:
  replicas: 1
  selector:
    app: httpd
  template: 
    metadata:
      name: httpd-pod  
      labels:
       app: httpd
    spec:
      containers:
      - name: myhttpd
        image: httpd
        ports:
        - containerPort: 80
          hostPort: 80 