apiVersion: v1
kind: ReplicationController
metadata: 
  name: httpd-rc
  labels:
  author: kris
spec:
  replicas: 3
  template: 
    metadata:
      name: httpd-pod  
      labels:
      author: kris
    spec:
      containers:
      - name: myhttpd
        image: httpd
        ports:
        - containerPort: 80
          hostport: 8080